version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python:
    - six
    - psutil
  system: bindep.txt
  python_interpreter:
    package_system: "python39"
additional_build_steps:
  prepend_base: |
    RUN microdnf install gcc python3-devel pkg-config systemd-devel
  append_base:
    - RUN export CPPFLAGS=-I/usr/include/python3.6m/ &&/usr/bin/pip3 install systemd-python
options:
  package_manager_path: /usr/bin/microdnf