- name: Listen for events on kafka
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        port: 9092
        topic: imagens
        group_id: ansible-eda
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080

  rules:
    - name: kafka
      condition: event.message != ""
      action:
        run_job_template:
          name: StorageRemediation
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               sleep: 1
    - name: webhook
      condition: event.payload.message != ""
      action:
        run_job_template:
          name: StorageRemediation
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               sleep: 1
